services:
#  acme.demo:
#    class: Acme\DemoBundle\Service\Demo
#    arguments:
#      - %acme_demo_param%
#      - @another_service
#    tags:
#      - { name: tag.name, alias: acme_demo }

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }
  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }
